project_id = "obxqbuafuvgyyznmzeqi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.track-application]
verify_jwt = false

[functions.upload-document]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.submit-application]
verify_jwt = false